version: '3.8'

services:
  web:
    image: disester-management-app
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:5000"
    restart: on-failure  
    depends_on:
      - db
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dmb
      DB_PORT: 5432  
    networks:
      - backend
  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmb  
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
    driver: bridge